export interface Producto {
    n_id_producto: any,
    n_id_tipo_medida: number,
    n_id_grupo: number,
    n_id_proveedor: number,
    c_codigo_producto: string,
    c_nombre_producto: string,
    c_detalle_primario_producto: string,
    c_descripcion_producto: string,
    f_precio_producto: number,
    b_igv_producto: boolean,
    b_dolar_producto: boolean,
    b_par_producto: boolean,
    n_cantidad_viene_producto: number,
    n_precio_por_cantidad_viene_producto: number,
    n_id_producto_asociado: any,
    c_color:string,
    nombreProductoAsociado: any,
    n_stock1: number,
    n_stock2: number,
    n_stock3: number,
    c_fec_actu_stock1: string,
    c_fec_actu_stock2: string,
    c_fec_actu_stock3: string,
    n_pedido1: number,
    n_pedido1_local?: number,
    n_pedido2: number,
    n_pedido2_local?: number,
    n_pedido3: number,
    n_pedido3_local?: number,
    c_fec_actu_pedido1: string,
    c_fec_actu_pedido2: string,
    c_fec_actu_pedido3: string,
    caseGeneric: number,
    n_activo: number;
    c_descripcion_pedido: string,
    
}